# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'portSelectionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtSerialPort import QSerialPort, QSerialPortInfo
from PyQt5.QtCore import QIODevice
from mainWindow import Ui_MainWindow


class Ui_portSelection(object):
    serial = QSerialPort()
    serial.setBaudRate(115200)

    def search_serial_ports(self): # method of searching for list of available serial ports
        portlist = []
        for port in QSerialPortInfo().availablePorts():
            portlist.append(port.portName())
        return portlist
    
    def setupUi(self, portSelection):
        # window drawing
        portSelection.setObjectName("portSelection")
        portSelection.resize(311, 149)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(portSelection.sizePolicy().hasHeightForWidth())
        portSelection.setSizePolicy(sizePolicy)
        portSelection.setMinimumSize(QtCore.QSize(311, 149))
        portSelection.setMaximumSize(QtCore.QSize(311, 149))
        self.horizontalLayoutWidget = QtWidgets.QWidget(portSelection)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 50, 261, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_ports = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_ports.setObjectName("comboBox_ports")
        self.horizontalLayout.addWidget(self.comboBox_ports)
        self.pushButton_ok = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ok.sizePolicy().hasHeightForWidth())
        self.pushButton_ok.setSizePolicy(sizePolicy)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.label = QtWidgets.QLabel(portSelection)
        self.label.setGeometry(QtCore.QRect(20, 20, 281, 16))
        self.label.setObjectName("label")

        self.retranslateUi(portSelection)
        QtCore.QMetaObject.connectSlotsByName(portSelection)

        self.comboBox_ports.addItems(self.search_serial_ports()) # filling comboBox of ports
        self.pushButton_ok.clicked.connect(lambda: self.start_main_window())
        

    def retranslateUi(self, portSelection):
        _translate = QtCore.QCoreApplication.translate
        portSelection.setWindowTitle(_translate("portSelection", "Выбор COM-порта"))
        self.pushButton_ok.setText(_translate("portSelection", "OK"))
        self.label.setText(_translate("portSelection", "Выберете COM-порт для связи с микроконтроллером"))

    def start_main_window(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.MainWindow, self.comboBox_ports.currentText()) # opening the main window and specifying the selected port 
        self.MainWindow.show()
        portSelection.close()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    portSelection = QtWidgets.QWidget()
    ui = Ui_portSelection()
    ui.setupUi(portSelection)
    portSelection.show()
    sys.exit(app.exec_())
